import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import FeaturesSection from '../components/Features';
import HeroHeader from '../components/HeroHeader';
import TopNav from '../components/TopNav';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-full min-h-screen w-full flex-col items-start dark:bg-slateDark-4">
        <TopNav />
        <HeroHeader />
        <FeaturesSection />
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
